### ISSUE TITLE
Mesh nodes not set to correct gridfunction

### ISSUE THREAD

**Issue by rcarson3** [llnl/ExaConstit#32]
During my post processing updates, I noticed that the Jacobian calculations is using the beginning of time step coordinates rather than the end of time step coordinates of the mesh. I saw this in the deformation gradient calculations when it was giving me the previous time step values. I'm guessing this error was introduced at some point when doing all of the refactoring for the GPU stuff. Since, it was originally working correctly with the UMAT stuff based on the deformation gradients that were returned back then. Nominally, I wouldn't expect this to make a drastic difference if you have small time steps or going out to small strains. However, it'll definitely cause issues as your strains increase or you're taking large time steps.

I'll push a fix shortly and then will do a new release once I've quantified how a big a difference this makes for large strains. I'll probably do 2 commits for this. One with the fix and then one with the test rebases, so it's easier to see how things have changed.

**Comment by rcarson3** [comment]
This was fixed in the earlier commit, and it looks like for the loading direction that for deformations that were in the tens-hundreds of MPa that the values changed were in the KPa range for 1% strain. However, I'll take a look at something that out's to 20-30% where I take larger step sizes to see how big of a difference we're really at in the end. Hopefully, it's within 1% error. Nonetheless, I'll push out a new release this weekend once I've add in the functionality to also output the volume average deformation gradient, and if you're running ExaCMech models then the plastic work.

Also, I'll add a small mesh test out to larger strains that should make it more obvious if something is wrong, and hopefully prevent this from occurring again if we're refactoring things.

**Comment by rcarson3** [comment]
With the release of version 0.5.0 this is now fixed. This is the version recommend for people to now run.

Additionally, I did a few large monotonic tension tests out to 25% engineering strain for a copper sample and only noticed errors within 1% for the macroscopic response. However, I can't say how bad the difference might be for more complicated loading conditions or the intragrain response would be. If a user does see larger differences I would be interested to hear about it.

**Comment by nrbarton** [comment]
If this was the issue with the jacobian being wrong but the residual was still correct then you would expect differences in convergence rate but not in quality of the solution for well-converged solutions, right?

**Comment by rcarson3** [comment]
So, I think the converged solutions were close in the tests I was looking at for a few reasons. First, I think the fact that we're a velocity based code is a reason this wasn't caught sooner. I don't think I ever took more than a 1% strain step at a time, so the velocity gradients between time steps should be close in the fully developed plastic flow. Therefore, the stress should still be fairly close.

I've added a unit test that checks the volume average deformation gradient at each step to hopefully catch any potential future errors like this. Although, I don't think this should happen again as this was an artifact from when ExaConstit was using UMATs for things and we needed the beginning time step jacobians.

**Comment by nrbarton** [comment]
Ah — I thought you meant Jacobian just in the sense of the stiffness compression. Sounds like it was more than that.
