### ISSUE TITLE
Additional post-processing variables needed for a light-up script

### ISSUE THREAD

**Issue by rcarson3** [llnl/ExaConstit#40]
A typical light-up script would require an elements elastic strain tensor, lattice orientation, and element centroid to work. The element centroid and strain tensor are not currently outputted, but they should be easy enough to add. Although, the elastic strains from ECMech will require just a little bit of extra work as we'll need to add the volumetric contribution to the stored 5-vec form of the deviatoric elastic strain stored in the history variables. We also save off the relative volumetric expansion which will allow us to get at the volumetric strain as well.

**Comment by nrbarton** [comment]
In the babel-wrapped old evptn model in the mdef package, the getWtsOrsStretches method had machinery to convert to a strain tensor. That ended up being implemented in mspBEvpc_mspBEvpcEvptn_Impl.F90, and if it ends up being useful I can transcribe that coding into ExaCMech.

**Comment by rcarson3** [comment]
I'll take a look at those files, but I think at initially it shouldn't be too hard to implement a first pass of things into ExaConstit.
