### ISSUE TITLE
How to use exaconstit correctly in Windows environment

### ISSUE THREAD

**Issue by wonengkanjiannideyanjing** [llnl/ExaConstit#57]
I would like to know how to set up a project that uses ExaConstit and MFEM for temperature field simulation.I have never used this kind of software before, and I don't know how to proceed with the first step. Does anyone have any similar development experience that you can share with me?I have completed the installation on my local computer.

**Comment by rcarson3** [comment]
@wonengkanjiannideyanjing ExaConstit is not designed to perform thermo-mechanical or just basic heat transfer type problems. You might be better looking at something like Serac: https://github.com/LLNL/serac. I'm going to close this issue though as this sorta thing is outside of the scope of this codebase.
